import type { Metadata } from 'next'
import Link from "next/link"

export const metadata: Metadata = {
  title: 'Terms of Service – Zibly',
  description: 'Read the Zibly terms governing use of our AI-powered analytics platform and services.',
  alternates: { canonical: 'https://www.zibly.ai/terms' },
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="container max-w-4xl px-4 py-12 md:px-6 md:py-24">
        <div className="space-y-8">
          <div className="space-y-4">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl text-primary">Terms of Service</h1>
            <p className="text-gray-600">Last updated: December 2024</p>
          </div>

          <div className="space-y-6">
            {/* 1. Acceptance of Terms */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-primary">1. Acceptance of Terms</h2>
              <p className="text-gray-700">
                These Terms of Service ("Terms") constitute a legally binding agreement between you ("User," "you," or "your") and Zibly, Inc. ("Zibly," "we," "our," or "us") governing your access to and use of the Zibly.ai platform, website, and any related services (collectively, the "Service"). By creating an account, submitting data, or using any part of the Service, you acknowledge that you have read, understood, and agree to be bound by these Terms, our <Link href="/privacy" className="text-primary underline">Privacy Policy</Link>, and any additional guidelines or rules posted on the Service. If you do not agree with these Terms, you may not use the Service.
              </p>
            </section>

            {/* 2. Eligibility and Account Registration */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-primary">2. Eligibility and Account Registration</h2>
              <p className="text-gray-700">
                The Service is intended for business and professional use by individuals aged 18 or older. By registering, you represent that you are at least 18 years of age, and have the legal capacity and authority to enter into these Terms on behalf of yourself or your organization. You are responsible for providing accurate and complete registration information and for maintaining the confidentiality and security of your account credentials. You must promptly notify us of any unauthorized use or suspected breach of your account.
              </p>
            </section>

            {/* 3. Description of Service & AI Technology */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-primary">3. Description of Service & AI Technology</h2>
              <p className="text-gray-700">
                Zibly is an AI-powered analytics and automation platform that enables you to upload or submit business data, documents, or instructions ("User Content") and receive back work products, reports, analyses, or written content generated by our system ("Outputs").
              </p>
              <p className="text-gray-700">
                <strong>AI Providers:</strong> You acknowledge that the Service utilizes artificial intelligence technology provided by third-party providers (including, but not limited to, OpenAI, Anthropic, Google, and Amazon Web Services). While we select providers with high security standards, the underlying nature of Large Language Models (LLMs) means Outputs are probabilistic and may occasionally contain inaccuracies.
              </p>
            </section>

            {/* 4. Permitted and Prohibited Uses */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-primary">4. Permitted and Prohibited Uses</h2>
              <p className="text-gray-700">
                You agree to use the Service only for lawful business purposes. You may not:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>Use the Service for any unlawful, harmful, fraudulent, infringing, or abusive activity.</li>
                <li>Upload, submit, or transmit any content that is illegal, obscene, defamatory, or that violates any third-party rights.</li>
                <li>Attempt to probe, scan, or test the vulnerability of the Service, breach security, or circumvent authentication measures.</li>
                <li>Interfere with, disrupt, or negatively affect the integrity or performance of the Service or its underlying infrastructure.</li>
                <li>Use the Service for competitive analysis, reverse engineering, or to build a competing product.</li>
                <li>Share, sell, rent, or sublicense the Service or its Outputs to unauthorized third parties.</li>
              </ul>
            </section>

            {/* 5. User Content, Data Security, and AI Training */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-primary">5. User Content, Data Security, and AI Training</h2>
              <p className="text-gray-700 font-medium bg-blue-50 p-4 rounded-lg border border-blue-200">
                This section contains important information about how we handle your data and our commitment to not using it for AI training.
              </p>

              <div className="space-y-4">
                <div>
                  <h3 className="text-lg font-semibold text-primary">5.1 Ownership of Content</h3>
                  <p className="text-gray-700">
                    You retain all right, title, and interest in and to any data, documents, or content you submit to the Service ("User Content").
                  </p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold text-primary">5.2 Ownership of Outputs</h3>
                  <p className="text-gray-700">
                    Subject to your compliance with these Terms, you own all rights, title, and interest in the Outputs generated specifically for you by the Service.
                  </p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold text-primary">5.3 License to Host</h3>
                  <p className="text-gray-700">
                    By submitting content, you grant Zibly a non-exclusive, worldwide, royalty-free license to use, host, store, process, transmit, and display your User Content solely for the purpose of providing the Service to you.
                  </p>
                </div>

                <div className="bg-green-50 p-4 rounded-lg border border-green-200">
                  <h3 className="text-lg font-semibold text-primary">5.4 No Training Covenant</h3>
                  <p className="text-gray-700">
                    <strong>Zibly covenants and agrees that we will not use your User Content or Outputs to train, fine-tune, or improve our proprietary artificial intelligence models or the models of our third-party providers.</strong> Your data is processed solely to generate the specific response you requested.
                  </p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold text-primary">5.5 Data Security</h3>
                  <p className="text-gray-700">
                    We implement industry-standard security measures designed to protect your data, including encryption in transit (TLS) and at rest (AES-256). Our infrastructure is hosted on SOC 2 Type II compliant cloud providers (AWS). See our <Link href="/security" className="text-primary underline">Security</Link> page for details.
                  </p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold text-primary">5.6 Confidentiality</h3>
                  <p className="text-gray-700">
                    Zibly treats your User Content as Confidential Information. Zibly's personnel are prohibited from accessing your content except: (a) where necessary to resolve technical support issues at your request; (b) to investigate security incidents; or (c) as required by law.
                  </p>
                </div>
              </div>
            </section>

            {/* 6. Fees, Payment, and Subscription */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-primary">6. Fees, Payment, and Subscription</h2>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>
                  <strong>Billing:</strong> Subscription fees are billed in advance on a recurring basis.
                </li>
                <li>
                  <strong>Renewals/Cancellations:</strong> Subscriptions automatically renew unless canceled. You may cancel at any time.
                </li>
                <li>
                  <strong>Refunds:</strong> Fees are non-refundable except as required by law.
                </li>
                <li>
                  <strong>Taxes:</strong> You are responsible for applicable taxes.
                </li>
              </ul>
            </section>

            {/* 7. Intellectual Property */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-primary">7. Intellectual Property</h2>
              <p className="text-gray-700">
                All Zibly trademarks, software code, interface designs, and platform features are owned by Zibly. No rights are granted except as expressly set forth in these Terms.
              </p>
            </section>

            {/* 8. Service Availability and Modifications */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-primary">8. Service Availability and Modifications</h2>
              <p className="text-gray-700">
                Zibly strives for high reliability but does not guarantee 100% uptime. We may modify or discontinue features at any time. We are not liable for any loss caused by service interruptions or data loss derived from outages at our third-party cloud or AI providers.
              </p>
            </section>

            {/* 9. Third-Party Services */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-primary">9. Third-Party Services</h2>
              <p className="text-gray-700">
                The Service integrates with third-party platforms and LLM providers. Zibly is not responsible for the independent acts or omissions of these third parties, though we maintain strict Data Processing Agreements (DPAs) with all sub-processors to ensure data safety.
              </p>
            </section>

            {/* 10. Disclaimers and AI Limitations */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-primary">10. Disclaimers and AI Limitations</h2>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>
                  <strong>10.1 As-Is Basis:</strong> The Service is provided "as is" without warranties of any kind.
                </li>
                <li>
                  <strong>10.2 AI Hallucinations & Accuracy:</strong> You acknowledge that AI systems can suffer from "hallucinations" (generating plausible-sounding but incorrect information). You are solely responsible for verifying the accuracy, completeness, and suitability of any Output before using it for professional, financial, or legal purposes.
                </li>
                <li>
                  <strong>10.3 No Professional Advice:</strong> Outputs generated by Zibly do not constitute professional legal, accounting, or financial advice. Zibly is a tool to assist professionals, not a replacement for professional judgment.
                </li>
              </ul>
            </section>

            {/* 11. Limitation of Liability */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-primary">11. Limitation of Liability</h2>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>
                  <strong>11.1 Indirect Damages:</strong> To the fullest extent permitted by law, Zibly shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits.
                </li>
                <li>
                  <strong>11.2 Cap on Damages:</strong> In no event shall Zibly's aggregate liability to you exceed the greater of: (a) the total amount paid by you to Zibly in the twelve (12) months preceding the claim; or (b) $100.00.
                </li>
              </ul>
            </section>

            {/* 12. Indemnification */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-primary">12. Indemnification</h2>
              <p className="text-gray-700">
                You agree to indemnify and hold harmless Zibly from any claims, damages, or expenses arising from your use of the Service, your User Content, or your violation of these Terms.
              </p>
            </section>

            {/* 13. Suspension and Termination */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-primary">13. Suspension and Termination</h2>
              <p className="text-gray-700">
                We reserve the right to suspend or terminate your access for violation of these Terms. Upon termination, we will delete your User Content in accordance with our retention policies.
              </p>
            </section>

            {/* 14. Governing Law and Dispute Resolution */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-primary">14. Governing Law and Dispute Resolution</h2>
              <p className="text-gray-700">
                These Terms are governed by the laws of the State of Florida. Any legal action shall be brought exclusively in the courts located in Miami-Dade County, Florida.
              </p>
            </section>

            {/* 15. Changes to Terms */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-primary">15. Changes to Terms</h2>
              <p className="text-gray-700">
                We may update these Terms at any time. Continued use constitutes acceptance.
              </p>
            </section>

            {/* 16. Contact Information */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-primary">16. Contact Information</h2>
              <p className="text-gray-700">
                For security or legal questions: <Link href="mailto:security@zibly.ai" className="text-primary underline">security@zibly.ai</Link> or <Link href="mailto:support@zibly.ai" className="text-primary underline">support@zibly.ai</Link>.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}
