import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service – Zibly',
  description: 'Read the Zibly terms governing use of our email-powered AI colleague and services.',
  alternates: { canonical: 'https://zibly.ai/terms' },
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="container max-w-4xl px-4 py-12 md:px-6 md:py-24">
      <div className="space-y-8">
        <div className="space-y-4">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl text-primary">Terms of Service</h1>
          <p className="text-gray-600">Last updated: December 2024</p>
        </div>

        <div className="space-y-6">
          {/* Acceptance of Terms */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary">1. Acceptance of Terms</h2>
            <p className="text-gray-700">
              These Terms of Service ("Terms") constitute a legally binding agreement between you ("User," "you," or "your") and Zibly, Inc. ("Zibly," "we," "our," or "us") governing your access to and use of the Zibly.ai platform, website, and any related services (collectively, the "Service"). By creating an account, submitting data, or using any part of the Service, you acknowledge that you have read, understood, and agree to be bound by these Terms, our <a href="/privacy" className="text-primary underline">Privacy Policy</a>, and any additional guidelines or rules posted on the Service. If you do not agree with these Terms, you may not use the Service.
            </p>
          </section>

          {/* Eligibility & Account Registration */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary">2. Eligibility and Account Registration</h2>
            <p className="text-gray-700">
              The Service is intended for business and professional use by individuals aged 18 or older. By registering, you represent that you are at least 18 years of age, and have the legal capacity and authority to enter into these Terms on behalf of yourself or your organization. You are responsible for providing accurate and complete registration information and for maintaining the confidentiality and security of your account credentials. You must promptly notify us of any unauthorized use or suspected breach of your account.
            </p>
          </section>

          {/* Description of Service */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary">3. Description of Service</h2>
            <p className="text-gray-700">
              Zibly is an AI-powered analytics and automation platform that enables you to upload or submit business data, documents, or instructions ("User Content") and receive back work products, reports, analyses, or written content generated by our AI systems and human-in-the-loop operators ("Outputs"). The Service may be accessed via web, email, or other approved methods, and may evolve or change over time.
            </p>
          </section>

          {/* Permitted and Prohibited Uses */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary">4. Permitted and Prohibited Uses</h2>
            <p className="text-gray-700">
              You agree to use the Service only for lawful business purposes, in accordance with these Terms, applicable laws, and industry best practices. You may not:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>Use the Service for any unlawful, harmful, fraudulent, infringing, or abusive activity.</li>
              <li>Upload, submit, or transmit any content that is illegal, obscene, defamatory, or that violates any third-party rights.</li>
              <li>Attempt to probe, scan, or test the vulnerability of the Service, breach security, or circumvent authentication measures.</li>
              <li>Interfere with, disrupt, or negatively affect the integrity or performance of the Service or its underlying infrastructure.</li>
              <li>Use the Service for competitive analysis, reverse engineering, or to build a competing product.</li>
              <li>Share, sell, rent, or sublicense the Service or its Outputs to unauthorized third parties.</li>
              <li>Violate any applicable export, privacy, or intellectual property laws.</li>
            </ul>
          </section>

          {/* User Content, Outputs, and Data Rights */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary">5. User Content, Outputs, and Data Rights</h2>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>
                <strong>Your Content:</strong> You retain all right, title, and interest in and to any data, documents, or content you submit to the Service (“User Content”). By submitting content, you grant Zibly a non-exclusive, worldwide, royalty-free license to use, host, store, process, transmit, and display your User Content solely for the purpose of providing and improving the Service, resolving support requests, and as otherwise permitted by our Privacy Policy.
              </li>
              <li>
                <strong>Outputs:</strong> You own the Outputs generated specifically for you by the Service, subject to your compliance with these Terms. Zibly and its licensors retain all intellectual property rights in the underlying software, algorithms, templates, and platform.
              </li>
              <li>
                <strong>Data Security:</strong> We implement industry-standard security measures to protect your data, including encryption in transit and at rest. See our <a href="/security" className="text-primary underline">Security</a> page for details.
              </li>
              <li>
                <strong>Confidentiality:</strong> We do not use your User Content to train public AI models, and do not sell your data to third parties. Zibly’s personnel are required to keep your information confidential and only access it to provide support or resolve technical issues.
              </li>
              <li>
                <strong>Data Deletion:</strong> You may request deletion of your account or content at any time by contacting <a href="mailto:support@zibly.ai" className="text-primary underline">support@zibly.ai</a>. We will delete your information from our active systems within 7 business days unless otherwise required by law.
              </li>
            </ul>
          </section>

          {/* Fees, Payment, and Subscription */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary">6. Fees, Payment, and Subscription</h2>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>
                <strong>Billing:</strong> Zibly offers both free and paid subscription plans. Subscription fees are billed in advance, on a recurring monthly or annual basis, based on the plan you select. All payments must be made in U.S. dollars.
              </li>
              <li>
                <strong>Renewals and Cancellations:</strong> Your subscription will automatically renew unless you cancel before the renewal date. You may cancel at any time, and your access will continue until the end of the current billing period.
              </li>
              <li>
                <strong>Refunds:</strong> Except as required by law, all fees are non-refundable. Zibly reserves the right to change its fees at any time with at least 30 days’ advance notice for existing subscribers.
              </li>
              <li>
                <strong>Taxes:</strong> You are responsible for any applicable taxes, levies, or duties imposed by taxing authorities.
              </li>
            </ul>
          </section>

          {/* Intellectual Property and License */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary">7. Intellectual Property and License</h2>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>
                <strong>Platform IP:</strong> All Zibly trademarks, content, software, and platform features are owned by Zibly or its licensors. Except for your rights in User Content and Outputs as described above, no rights are granted except as expressly set forth in these Terms.
              </li>
              <li>
                <strong>Limited License:</strong> Zibly grants you a limited, non-exclusive, non-transferable, revocable license to use the Service solely for your internal business purposes and in accordance with these Terms.
              </li>
            </ul>
          </section>

          {/* Service Availability, Modifications, and Support */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary">8. Service Availability, Modifications, and Support</h2>
            <p className="text-gray-700">
              Zibly strives for high reliability but does not guarantee that the Service will always be available or free from interruptions, errors, or data loss. We may modify, update, or discontinue any aspect of the Service at any time, with or without notice. We may provide technical support at our discretion and reserve the right to limit support for certain plans or features.
            </p>
          </section>

          {/* Third-Party Services and Integrations */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary">9. Third-Party Services and Integrations</h2>
            <p className="text-gray-700">
              The Service may integrate with third-party platforms, APIs, or data sources. Zibly is not responsible for the availability, accuracy, or security of such third-party services, and your use of them is governed by their respective terms and policies.
            </p>
          </section>

          {/* Disclaimers */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary">10. Disclaimers</h2>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>
                <strong>As-Is Basis:</strong> The Service and all Outputs are provided “as is” and “as available,” without warranties of any kind, whether express, implied, or statutory.
              </li>
              <li>
                <strong>No Professional Advice:</strong> Outputs generated by Zibly, including analytics, reports, or written content, are for informational purposes only and should not be relied upon as professional, legal, investment, or business advice.
              </li>
              <li>
                <strong>No Warranty:</strong> Zibly makes no warranty as to the accuracy, completeness, or suitability of Outputs, and does not guarantee that the Service will be uninterrupted, secure, or error-free.
              </li>
            </ul>
          </section>

          {/* Limitation of Liability */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary">11. Limitation of Liability</h2>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>
                <strong>Indirect Damages:</strong> To the fullest extent permitted by law, Zibly shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly.
              </li>
              <li>
                <strong>Cap on Damages:</strong> In no event shall Zibly’s aggregate liability to you exceed the total amount paid by you to Zibly in the twelve (12) months preceding the claim.
              </li>
              <li>
                <strong>Jurisdictional Limits:</strong> Some jurisdictions do not allow exclusion or limitation of liability for consequential or incidental damages; the above limitations may not apply to you.
              </li>
            </ul>
          </section>

          {/* Indemnification */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary">12. Indemnification</h2>
            <p className="text-gray-700">
              You agree to indemnify, defend, and hold harmless Zibly, its officers, directors, employees, agents, and affiliates from any and all claims, damages, obligations, losses, liabilities, costs, or expenses (including attorney’s fees) arising from your use of the Service, your violation of these Terms, or your violation of any law or rights of a third party.
            </p>
          </section>

          {/* Suspension and Termination */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary">13. Suspension and Termination</h2>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>
                <strong>Termination by You:</strong> You may cancel your account or subscription at any time. Upon termination, your right to use the Service will cease, but the terms of this Agreement (including ownership, confidentiality, and limitation of liability) will continue as applicable.
              </li>
              <li>
                <strong>Suspension/Termination by Us:</strong> We reserve the right to suspend or terminate your access to the Service at any time, with or without notice, for violation of these Terms, misuse, or to protect the integrity and security of the Service.
              </li>
              <li>
                <strong>Effect of Termination:</strong> Upon termination, we will delete your User Content as described in Section 5 unless required by law to retain it.
              </li>
            </ul>
          </section>

          {/* Governing Law and Dispute Resolution */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary">14. Governing Law and Dispute Resolution</h2>
            <p className="text-gray-700">
              These Terms, and any dispute arising out of or relating to these Terms or the Service, are governed by and construed in accordance with the laws of the State of Florida, without regard to conflict of laws principles. You agree that any legal action or proceeding related to the Service shall be brought exclusively in the federal or state courts located in Miami-Dade County, Florida, and you consent to the personal jurisdiction of such courts.
            </p>
          </section>

          {/* Changes to Terms */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary">15. Changes to Terms</h2>
            <p className="text-gray-700">
              We may update or modify these Terms at any time. We will provide notice of material changes via the Service or by email. Your continued use of the Service after any changes constitutes acceptance of the new Terms. If you do not agree to the updated Terms, you must stop using the Service.
            </p>
          </section>

          {/* Contact Information */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary">16. Contact Information</h2>
            <p className="text-gray-700">
              If you have any questions about these Terms of Service or your rights and obligations under them, please contact us at <a href="mailto:support@zibly.ai" className="text-primary underline">support@zibly.ai</a>.
            </p>
          </section>
        </div>
      </div>
      </div>
    </div>
  )
}
